after prix italia 2013

diff --git a/www/cgi-bin/combine/combine b/www/cgi-bin/combine/combine
--- a/www/cgi-bin/combine/combine
+++ b/www/cgi-bin/combine/combine
@@ -368,17 +368,67 @@ else
 					exit 5
 				endif
 				set actionmismatch =  `grep -c "ActionMismatch:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$`
-				if ( $actionmismatch ) then
-					echo "500"
-					echo "Server Error"
-					echo "Unsupported Action mismatch between $psource and $ptransf for $instance and $contract"
-					grep "ActionMismatch:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$ 
-					cp $repo/pprights/.tmp/$instance.$$.bak $repo/pprights/$instance
-					exit 55
+				if ( $actionmismatch ) then	#MOLTA ATT MICA BUONO ANCORA#
+					set wideclassiri = `grep "ActionMismatch:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$ | cut -f2`
+					set narrowclassiri = `grep "ActionMismatch:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$ | cut -f3`
+#
+#					3.A. Get list of Actions resulting from difference in hierarchy (assuming rightscompare was okay)
+					xsltproc --stringparam wideclassiri "$wideclassiri" \
+						--stringparam narrowclassiri "$narrowclassiri" \
+						$pdir/xsl/DiffClassHierarchy.xsl $pdir/share/ppavro.owl > $repo/pprights/.tmp/diffactions.$ploop.$sloop.$$
+					set ret = $?
+					if ( $ret ) then
+        					echo "500"
+        					echo "Server Error"
+						echo "$this failed in getting difference in actions  ($wideclassiri,$narrowclassiri) related to ($psource,$ptransf) for $instance and $contract"
+						cp $repo/pprights/.tmp/$instance.$$.bak $repo/pprights/$instance
+						exit 5
+					endif
+					set diffActions = `cat $repo/pprights/.tmp/diffactions.$ploop.$sloop.$$`
+					set daction = 1
+					cp $repo/pprights/.tmp/$instance.psource.$ploop.$sloop.$$ $repo/pprights/.tmp/$instance.psource.$ploop.$sloop.action.$$
+#					3.B. For each Action
+					foreach diffAct ( $diffActions )
+#					Using permission extracted from Holdings 
+#					3.B.1 Rename Permission/Action individuals, as well as Class of Action
+						xsltproc --stringparam perm $psource \
+							--stringparam newindbase da$daction  \
+							--stringparam newactionclass $diffAct  \
+						$pdir/xsl/renamePermissionAction.xsl \
+						$repo/pprights/.tmp/$instance.psource.$ploop.$sloop.action.$$ > $repo/pprights/.tmp/$instance.psource.$ploop.$sloop.a$daction.$$
+						set ret = $?
+						if ( $ret ) then
+        						echo "500"
+        						echo "Server Error"
+							echo "$this failed in renaming Permission/Action individuals ($psource,$ptransf,$daction,$diffAct) for $instance and $contract"
+							cp $repo/pprights/.tmp/$instance.$$.bak $repo/pprights/$instance
+							exit 5
+						endif
+#					3.B.2 Add results to Holdings
+						xsltproc --stringparam extinstance $repo/pprights/.tmp/$instance.psource.$ploop.$sloop.a$daction.$$ \
+					$pdir/xsl/mergeWithInstance.xsl $repo/pprights/.tmp/$instance.without.psource.$ploop.$sloop.$$ > $repo/pprights/.tmp/$instance.without.psource.$ploop.$sloop.$$.tmp
+						set ret = $?
+						if ( $ret ) then
+							echo "500"
+							echo "Server Error"
+							echo "$this could not merge $instance.psource.$ploop.$sloop.a$daction.$$ into $repo/pprights/.tmp/$instance.without.psource.$ploop.$sloop.$$"
+							cp $repo/pprights/.tmp/$instance.$$.bak $repo/pprights/$instance
+							exit 5
+						endif
+						mv $repo/pprights/.tmp/$instance.without.psource.$ploop.$sloop.$$.tmp $repo/pprights/.tmp/$instance.without.psource.$ploop.$sloop.$$
+						@ daction ++
+					end
+#
+				#	echo "500"
+				#	echo "Server Error"
+				#	echo "Unsupported Action mismatch between $psource and $ptransf for $instance and $contract"
+				#	grep "ActionMismatch:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$ 
+				#	cp $repo/pprights/.tmp/$instance.$$.bak $repo/pprights/$instance
+				#	exit 55
 				endif
 				set numdiff = `grep -c "Fact:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$`
 				set diffFacts = `grep "Fact:" $repo/pprights/.tmp/diff.$ploop.$sloop.$$ | cut -f2` 
-#				4.A. If NO Difference. Source is sold without remaining
+#				4.A. If NO Difference. Source is sold without remaining (related to Facts)
 #				4.B. If Difference. Make Foreach
 				set obj = "http://purl.oclc.org/NET/mvco.owl#hasRequired"
 				set dfact = 1
diff --git a/www/cgi-bin/mkr/addkp b/www/cgi-bin/mkr/addkp
--- a/www/cgi-bin/mkr/addkp
+++ b/www/cgi-bin/mkr/addkp
@@ -1,9 +1,9 @@
 #!/bin/tcsh -f
 #  rightsdraw
-#  Version: 2.0.1
+#  Version: 2.0.2
 #  Authors: L. Boch
 #
-#  Copyright (C) 2010-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
+#  Copyright (C) 2010-2013 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -19,8 +19,15 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 set echo_style = both
-echo "content-type: text/html\n"
-set repo = $pdir/users/$puser/repo/pprights
+q
+echo "content-type: text/plain\n"
+# WARNING
+# this MKR service can also be used by MCO context
+#  => if setting of mcomode is not suitable to MKR context, this will give misfunctioning
+# this was done for limiting changes to MKR services
+#
+set mcomode = `cat $pdir/users/$puser/config/mcomode`
+set repo = $pdir/users/$puser/repo/$mcomode
 set mykpr = `cat $pdir/users/$puser/config/mykpr`
 set this = `basename $0`
 if ( $REQUEST_METHOD != "GET" ) then
@@ -38,6 +45,7 @@ echo $inquery >> $pdir/logs/$this.$$.input
 set instance = "null"
 set kp = "null"
 ################################
+set handle = "null"
 set isexclusive = "null"
 set hassublicense = "null"
 set contract = "null"
@@ -47,7 +55,7 @@ set beforedate = "null"
 set negativetemporalcontext = "no"
 set territories = "null"
 set negativespatialcontext = "no"
-set languanges = "null"
+set languages = "null"
 set negativelanguages = "no"
 set maxlength = "null"
 set partofipentitycontext = "null"
@@ -66,7 +74,10 @@ set usepercentage = "null"
 set incomepercentage = "null"
 set i = 1
 while ( $i < $#inquery )
-        if ( "$inquery[$i]" == "instance" ) then
+        if ( "$inquery[$i]" == "handle" ) then
+                @ i++
+                set handle = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "instance" ) then
                 @ i++
                 set instance = "$inquery[$i]"
         else if ( "$inquery[$i]" == "kp" ) then
@@ -206,14 +217,19 @@ if ( $ret ) then
 	echo "$this could not get permitted actions for kp $kp"
 	exit 5
 endif
+# Se manca handle
 # trovare tutte le IPEntities in instance
-set instanceipentities = `xsltproc --stringparam classname IPEntity $pdir/xsl/getIndividualsOfClass.xsl $repo/$instance | sort -u`
-set ret = $?
-if ( $ret ) then
-	echo "500"
-	echo "Server Error"
-	echo "$this could not get ipenties for instance $instance"
-	exit 6
+if ( "$handle" == null ) then
+	set instanceipentities = `xsltproc --stringparam classname IPEntity $pdir/xsl/getIndividualsOfClass.xsl $repo/$instance | sort -u`
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this could not get ipenties for instance $instance"
+		exit 6
+	endif
+else 
+	set instanceipentities = "$handle"
 endif
 # from here down we are going to modify our instance
 # making a bak copy
