v 2.0.2 Aug 2013

diff --git a/www/cgi-bin/mco/addfacts b/www/cgi-bin/mco/addfacts
--- a/www/cgi-bin/mco/addfacts
+++ b/www/cgi-bin/mco/addfacts
@@ -1,9 +1,9 @@
 #!/bin/tcsh -f
 #  rightsdraw
-#  Version: 2.0.1
+#  Version: 2.0.2
 #  Authors: L. Boch
 #
-#  Copyright (C) 2010-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
+#  Copyright (C) 2010-2013 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -19,7 +19,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 set echo_style = both
-echo "content-type: text/html\n"
+echo "content-type: text/plain\n"
 set mcomode = `cat $pdir/users/$puser/config/mcomode`
 set repo = $pdir/users/$puser/repo/$mcomode
 set colors = `cat $pdir/users/$puser/config/colors`
@@ -45,6 +45,9 @@ set device = "null"
 set usertimeaccess = "null"
 set relatedaction = "null"
 set channels = "null"
+set maxlength = "null"
+set partofipentitycontext = "null"
+set negativepartofipentitycontext = "no"
 set negativechannels = "no"
 set negativeaccesspolicy = "no"
 set negativeserviceaccesspolicy = "no" 
@@ -116,6 +119,15 @@ while ( $i < $#inquery )
         else if ( "$inquery[$i]" == "channels" ) then
                 @ i++
                 set channels = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "maxlength" ) then
+                @ i++
+                set maxlength = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "partofipentitycontext" ) then
+                @ i++
+                set partofipentitycontext = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "negativepartofipentitycontext" ) then
+                @ i++
+                set negativepartofipentitycontext = "$inquery[$i]"
         else if ( "$inquery[$i]" == "negativechannels" ) then
                 @ i++
                 set negativechannels = "$inquery[$i]"
@@ -276,7 +288,7 @@ if ( $numruns != null ) then
 	echo $xnum > $pdir/users/$puser/config/inumber
 	set twoname = "#x$xnum"
 	set twoclass = "urn:mpeg:mpeg21:mco:ipre:2012#Run"
-	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative $negative $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative no $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
 	set ret = $?
 	if ( $ret ) then
 		echo "500"
@@ -395,6 +407,38 @@ if ( $territories != null ) then
 	endif
 	mv $repo/.tmp.$instance $repo/$instance
 endif
+if ( $maxlength != null ) then
+#	create Length
+	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
+	@ xnum ++
+	echo $xnum > $pdir/users/$puser/config/inumber
+	set twoname = "#x$xnum"
+	set twoclass = "urn:mpeg:mpeg21:mco:ipre:2012#Length"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative no $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+#	add Data Properties
+	set owner = $twoname
+	set key = "urn:mpeg:mpeg21:mco:ipre:2012#hasMaxLength"
+	set value = $maxlength
+	xsltproc --stringparam owner $owner --stringparam key $key --stringparam value $value $pdir/xsl/addDataProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addDataProperty ($owner, $key, $value) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+endif
 if ( $channels != null ) then
 #	create Channels 
 	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
@@ -422,6 +466,38 @@ if ( $channels != null ) then
 		echo "500"
 		echo "Server Error"
 		echo "$this failed on addDataProperty ($owner, $key, $value) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+endif
+if ( $partofipentitycontext != null ) then
+#	create IPEntity context
+	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
+	@ xnum ++
+	echo $xnum > $pdir/users/$puser/config/inumber
+	set twoname = "#x$xnum"
+	set twoclass = "urn:mpeg:mpeg21:mco:ipre:2012#IPEntityContext"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative $negativepartofipentitycontext $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+	set one = "#x$xnum"
+	set twoname = "$partofipentitycontext"
+	set twoclass = "http://purl.oclc.org/NET/mvco.owl#IPEntity"
+	set obj = "urn:mpeg:mpeg21:mco:ipre:2012#partOf"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative no $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
 		cp $repo/.tmp/$instance.$$.bak $repo/$instance
 		exit 8
 	endif
diff --git a/www/cgi-bin/mco/export b/www/cgi-bin/mco/export
--- a/www/cgi-bin/mco/export
+++ b/www/cgi-bin/mco/export
@@ -1,9 +1,9 @@
 #!/bin/tcsh -f
 #  rightsdraw
-#  Version: 2.0.1
+#  Version: 2.0.2
 #  Authors: L. Boch
 #
-#  Copyritght (C) 2012-2013 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
+#  Copyright (C) 2010-2013 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -19,11 +19,12 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 set echo_style = both
-echo "content-type: text/xml\n"
 set mcomode = `cat $pdir/users/$puser/config/mcomode`
 set repo = $pdir/users/$puser/repo/$mcomode
+set format = "OWL/XML"
 set this = `basename $0`
 if ( $REQUEST_METHOD != "GET" ) then
+	echo "content-type: text/plain\n"
 	echo "400"
 	echo "Bad request "
 	echo "$this accept only GET"
@@ -39,7 +40,13 @@ while ( $i < $#inquery )
         if ( "$inquery[$i]" == "instance" ) then
                 @ i++
                 set instance = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "format" ) then
+                @ i++
+                if ( "$inquery[$i]" == "OWL/XML" ||  "$inquery[$i]" == "RDF/XML" || "$inquery[$i]" == "CEL/XML" ) then
+			set format = "$inquery[$i]"
+		endif
         else
+		echo "content-type: text/plain\n"
 		echo "400"
 		echo "Bad request "
 		echo "$this Unknown input parameter: $inquery[$i]"
@@ -50,13 +57,56 @@ end
 set ret = 0
 #Sanity check
 if ( !( -ersf "$repo/$instance" ) ) then
+	echo "content-type: text/plain\n"
 	echo "404"
 	echo "Not Found "
 	echo "$this $repo/$instance"
 	exit 2
 endif
 #cp $repo/$instance $export/$instance
-cat $repo/$instance
+if ( "$format" == "OWL/XML" ) then
+	echo "content-type: text/xml\n"
+	cat $repo/$instance
+else if ( -ersf $pdir/lib/mcoserializationconverter ) then
+	set result = $pdir/logs/$this.$$.result
+	$pdir/lib/mcoserializationconverter $repo/$instance $result
+	set ret = $?
+	if ( $ret ) then
+		echo "content-type: text/plain\n"
+		echo "500"
+		echo "Server Error"
+		cat $result
+	else
+		if ( "$format" == "RDF/XML" ) then
+			echo "content-type: text/xml\n"
+			cat $result
+		else if ( -ersf $pdir/lib/mco2cel ) then
+			$pdir/lib/mco2cel $result $result.cel
+			set ret = $?
+			if ( $ret ) then
+				echo "content-type: text/plain\n"
+				echo "500"
+				echo "Server Error"
+				cat $result.cel
+			else
+				echo "content-type: text/xml\n"
+				cat $result.cel
+			endif
+		else
+			echo "content-type: text/plain\n"
+			echo "501"
+			echo "Not Implemented"
+			echo "mco2cel plugin not found"
+			exit 23
+		endif
+	endif
+else
+	echo "content-type: text/plain\n"
+	echo "501"
+	echo "Not Implemented"
+	echo "mcoserializationconverter plugin not found"
+	exit 22
+endif
 set ret = $?
 if ( $ret ) then
 	echo "500"
@@ -65,3 +115,4 @@ if ( $ret ) then
 	exit 3
 endif
 exit 0
+
diff --git a/www/cgi-bin/mco/list b/www/cgi-bin/mco/list
--- a/www/cgi-bin/mco/list
+++ b/www/cgi-bin/mco/list
@@ -1,9 +1,9 @@
 #!/bin/tcsh -f
 #  rightsdraw
-#  Version: 2.0.1
+#  Version: 2.0.2
 #  Authors: L. Boch
 #
-#  Copyright (C) 2010-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
+#  Copyright (C) 2010-2013 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -18,10 +18,10 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 set echo_style = both
-set mykpr = `cat $pdir/users/$puser/config/mykpr`
-echo "content-type: text/html\n"
+echo "content-type: text/plain\n"
+set mcomode = `cat $pdir/users/$puser/config/mcomode`
+set repo = $pdir/users/$puser/repo/$mcomode
 set this = `basename $0`
 if ( $REQUEST_METHOD != "GET" ) then
 	echo "400"
@@ -33,46 +33,37 @@ endif
 
 set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut -d'=' -f1- --output-delimiter=' '`
 set inquery = `$pdir/bin/clean.querystring $inquery`
-set form = "null"
+set instance = "null"
 set i = 1
 while ( $i < $#inquery )
-        if ( "$inquery[$i]" == "form" ) then
+        if ( "$inquery[$i]" == "repo" ) then
                 @ i++
-                set form = "$inquery[$i]"
+                set repo = $pdir/users/$puser/repo/$inquery[$i]
         else
 		echo "400"
 		echo "Bad request "
-		echo "$this unknown $inquery[$i]"
+		echo "$this Unknown input parameter: $inquery[$i]"
                 exit 1
         endif
         @ i++
 end
-#Sanity Check
-if ( !(-ersf $pdir/share/$form) ) then
+set ret = 0
+#Sanity check
+if ( !( -e "$repo" ) ) then
 	echo "404"
-	echo "Not Found $form"
+	echo "Not Found "
+	echo "$this $repo"
 	exit 2
 endif
-if ( $form != "query-kpr-form.html" ) then
-	cat $pdir/share/$form
-else
-	set mylist = `setenv QUERY_STRING "folder=$mykpr" ; $pdir/www/cgi-bin/kpr/list | awk 'FNR>1'`
-	set ret = $?
-	if ( $ret ) then
-	        echo "500"
-	        echo "Server Error"
-		echo "$this got $ret from listing kp from $mykpr"
-	else if ( "$mylist[1]" != 200 ) then
-		echo "$mylist"
-	else
-		#Got Success
-		set loop = 3
-		set options = ""
-		while ( $loop <= $#mylist )
-			set options = "$options<option>$mylist[$loop]<\/option>"
-			@ loop++
-		end
-		cat $pdir/share/$form | sed -e s/'+++kproptions+++'/$options/g
-	endif
+ls -1 $repo > $pdir/logs/$this.$$
+set ret = $?
+if ( $ret ) then
+	echo "500"
+	echo "Server error "
+	echo "$this $ret"
+	exit 3
 endif
+echo "200"
+echo "Success"
+cat $pdir/logs/$this.$$
 exit 0
diff --git a/www/cgi-bin/mkr/addkp b/www/cgi-bin/mkr/addkp
--- a/www/cgi-bin/mkr/addkp
+++ b/www/cgi-bin/mkr/addkp
@@ -49,6 +49,9 @@ set territories = "null"
 set negativespatialcontext = "no"
 set languanges = "null"
 set negativelanguages = "no"
+set maxlength = "null"
+set partofipentitycontext = "null"
+set negativepartofipentitycontext = "no"
 set channels = "null"
 set negativechannels = "no"
 set numruns = "null"
@@ -138,6 +141,15 @@ while ( $i < $#inquery )
         else if ( "$inquery[$i]" == "incomepercentage" ) then
                 @ i++
                 set incomepercentage = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "maxlength" ) then
+                @ i++
+                set maxlength = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "partofipentitycontext" ) then
+                @ i++
+                set partofipentitycontext = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "negativepartofipentitycontext" ) then
+                @ i++
+                set negativepartofipentitycontext = "$inquery[$i]"
         else
 		echo "400"
 		echo "Bad request "
@@ -343,7 +355,7 @@ if ( "$contract" != null ) then
 endif
 ########################999
 #	create Fact Intersection 
-if ( $afterdate != null || $beforedate != null || $numruns != null || $languages != null || $territories != null  || $relatedaction != null || $channels != null ) then
+if ( $afterdate != null || $beforedate != null || $numruns != null || $languages != null || $territories != null || $relatedaction != null || $channels != null || $maxlength != null || $partofipentitycontext != null ) then
 	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
 	@ xnum ++
 	echo $xnum > $pdir/users/$puser/config/inumber
@@ -613,6 +625,38 @@ if ( $relatedaction != null && $relatedactionperm != null ) then
 	endif
 	mv $repo/.tmp/$instance $repo/$instance
 endif
+if ( $maxlength != null ) then
+#	create Length
+	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
+	@ xnum ++
+	echo $xnum > $pdir/users/$puser/config/inumber
+	set twoname = "#x$xnum"
+	set twoclass = "urn:mpeg:mpeg21:mco:ipre:2012#Length"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative no $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+#	add Data Properties
+	set owner = $twoname
+	set key = "urn:mpeg:mpeg21:mco:ipre:2012#hasMaxLength"
+	set value = $maxlength
+	xsltproc --stringparam owner $owner --stringparam key $key --stringparam value $value $pdir/xsl/addDataProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addDataProperty ($owner, $key, $value) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+endif
 if ( $channels != null ) then
 #	create Channels
 	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
@@ -644,6 +688,38 @@ if ( $channels != null ) then
 		exit 8
 	endif
 	mv $repo/.tmp/$instance $repo/$instance
+endif
+if ( $partofipentitycontext != null ) then
+#	create IPEntity context
+	set xnum = `cat $pdir/users/$puser/config/inumber|bc`
+	@ xnum ++
+	echo $xnum > $pdir/users/$puser/config/inumber
+	set twoname = "#x$xnum"
+	set twoclass = "urn:mpeg:mpeg21:mco:ipre:2012#IPEntityContext"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative $negativepartofipentitycontext $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
+	set one = "#x$xnum"
+	set twoname = "$partofipentitycontext"
+	set twoclass = "http://purl.oclc.org/NET/mvco.owl#IPEntity"
+	set obj = "urn:mpeg:mpeg21:mco:ipre:2012#partOf"
+	xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname --stringparam negative no $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+		cp $repo/.tmp/$instance.$$.bak $repo/$instance
+		exit 8
+	endif
+	mv $repo/.tmp.$instance $repo/$instance
 endif
 echo "200"
 echo "Success"
diff --git a/www/cgi-bin/query/checkwith b/www/cgi-bin/query/checkwith
--- a/www/cgi-bin/query/checkwith
+++ b/www/cgi-bin/query/checkwith
@@ -1,9 +1,9 @@
 #!/bin/tcsh -f
 #  rightsdraw
-#  Version: 2.0.1
+#  Version: 2.0.2
 #  Authors: L. Boch
 #
-#  Copyright (C) 2010-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
+#  Copyright (C) 2010-2013 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -18,11 +18,17 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+
 set echo_style = both
 echo "content-type: text/html\n"
 set repo = $pdir/logs
 set mykpr = `cat $pdir/users/$puser/config/mykpr`
 set owliriprefix =  `cat $pdir/users/$puser/config/owliriprefix`
+set p4enable = `cat $pdir/users/$puser/config/p4enable`
+set querymode = `cat $pdir/users/$puser/config/querymode`
+set p4serverurl = `cat $pdir/users/$puser/config/p4serverurl`
+set p4account = `cat $pdir/users/$puser/config/p4account`
+set curloptions = `cat $pdir/users/$puser/config/curloptions`
 set this = `basename $0`
 if ( $REQUEST_METHOD != "GET" ) then
 	echo "400"
@@ -36,6 +42,7 @@ set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut 
 set inquery = `$pdir/bin/clean.querystring $inquery`
 set kp = "null"
 
+set output = "html"
 set owner = "null"
 set ipentity = "null"
 set relid = "null"
@@ -157,6 +164,12 @@ while ( $i < $#inquery )
         else if ( "$inquery[$i]" == "relid" ) then
                 @ i++
                 set relid = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "querymode" ) then
+                @ i++
+                set querymode = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "output" ) then
+                @ i++
+                set output = "$inquery[$i]"
         else
 		echo "400"
 		echo "Bad request "
@@ -165,6 +178,18 @@ while ( $i < $#inquery )
         endif
         @ i++
 end
+#Sanity check
+if ( $querymode == "p4" && $p4enable != on ) then
+	echo "400"
+	echo "Bad request "
+	echo "$this p4 is not enabled for requested querymode"
+        exit 11
+else if ( $querymode != "p4" && $querymode != "local" ) then
+	echo "400"
+	echo "Bad request "
+	echo "$this unknown querymode $querymode"
+        exit 12
+endif
 #
 #create empty query
 set instance = $this.$$
@@ -531,59 +556,97 @@ if ( $ret ) then
 	echo "$this got $ret in creating query diagram"
 	exit 8
 endif
+
+if ( $querymode == "local" ) then
 #
 #	Implementing local query to local index
 #
-set localrepo = $pdir/users/$puser/repo/pprights
-set localindex = $localrepo/.rightsindex
+	set localrepo = $pdir/users/$puser/repo/pprights
+	set localindex = $localrepo/.rightsindex
 #$pdir/bin/rightscompare -disablecontexts -all $repo/$instance $localindex > $pdir/logs/$this.$$.rightscompare.out
-$pdir/bin/rightscompare  -all $repo/$instance $localindex > $pdir/logs/$this.$$.rightscompare.out
-set ret = $?
-if ( $ret ) then
-	echo "500"
-	echo "Server Error"
-	echo "$this got $ret in performing rights matching"
-	exit 9
-endif
+	$pdir/bin/rightscompare  -all $repo/$instance $localindex > $pdir/logs/$this.$$.rightscompare.out
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this got $ret in performing rights matching"
+		exit 9
+	endif
 #
 #	Creation of query results locally
 #
-set listaout = `grep true $pdir/logs/$this.$$.rightscompare.out|cut -d'|' -f2 | cut -d'#' -f1 |sort -u`
-echo '<html><body><b>Your query</b>'\
-	'<div style="clear:both"><iframe src="/rightsdraw2/query/'$instance.png'" height="144"></iframe>' \
-	'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/query/$instance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
-	'</div>' \
-	'<b>Found '$#listaout' items matching your query</b><hr/>'
-foreach localinstance ( $listaout )
-	$pdir/bin/mco.dosvg $localinstance
-	echo '<div style="clear:both"><div style="float:left">'$localinstance'<br/><iframe src="/rightsdraw2/mco/'$localinstance.png'" height="144"></iframe></div>' \
-	'<div style="float:left"><p><form target="main" action="../mco/viewedit"><input type="submit" value="viewedit"><input type="hidden" name="instance" value="'$localinstance'"></form>' \
-	'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/mco/$localinstance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
-	'</div></div>'
-end
-exit 0
-#
-#	Creation of query results locally
-#
-set listaout = `grep true $pdir/logs/$this.$$.rightscompare.out|cut -d'|' -f2 | cut -d'#' -f1 |sort -u`
-echo '<Results xmlns="http://www.prestoprime.eu/xsd/rightsquery"><Success>true</Success>' > $pdir/logs/$this.$$.results
-foreach row ( $listaout ) 
-	set localinstance = `echo $row |sed -e s/':'/'-'/g`.owl
-	$pdir/bin/mco.dosvg $localinstance
-	echo '<Row eeIdentifier="'$row'" rightsgraph="'/rightsdraw2/mco/$localinstance.png'"></Row>'  >> $pdir/logs/$this.$$.results
-end
-echo '</Results>' >> $pdir/logs/$this.$$.results
-#
+	set listaout = `grep true $pdir/logs/$this.$$.rightscompare.out|cut -d'|' -f2 | cut -d'#' -f1 |sort -u`
+	if ( "$output" == "html" ) then
+		echo '<html><body><b>Your query</b>'\
+		'<div style="clear:both"><iframe src="/rightsdraw2/query/'$instance.png'" height="144"></iframe>' \
+		'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/query/$instance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
+		'</div>' \
+		'<b>Found '$#listaout' items matching your query</b><hr/>'
+		foreach localinstance ( $listaout )
+			$pdir/bin/mco.dosvg $localinstance
+			echo '<div style="clear:both"><div style="float:left">'$localinstance'<br/><iframe src="/rightsdraw2/mco/'$localinstance.png'" height="144"></iframe></div>' \
+			'<div style="float:left"><p><form target="rightsdraw2_main" action="../mco/viewedit"><input type="submit" value="viewedit"><input type="hidden" name="instance" value="'$localinstance'"></form>' \
+			'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/mco/$localinstance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
+			'</div></div>'
+		end
+		echo '</body></html>'
+	else
+		echo "200\nSuccess\n$listaout"
+	endif	
+else if ( $querymode == "p4" && $p4enable == "on" ) then
+#Posting the query and Getting jobid
+	curl -F rightsFile=@$repo/$instance $p4serverurl/wf/execute/query_rights -o $pdir/logs/$this.$$.job -H "userID:${p4account}" $curloptions
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed posting the query to $p4serverurl, got $ret."
+		exit 9
+	endif
+#Getting status
+	set try = 1
+	set maxtries = 4
+	while ( $try < $maxtries )
+		curl $p4serverurl/wf/`cat $pdir/logs/$this.$$.job`/status -o $pdir/logs/$this.$$.status.$try -H "userID:${p4account}" $curloptions
+		set ret = $?
+		if ( $ret ) then
+			echo "500"
+			echo "Server Error"
+			echo "$this failed in getting the query status from $p4serverurl, got $ret."
+			exit 9
+		endif
+		set iscompleted = `grep -c 'status="completed"' $pdir/logs/$this.$$.status.$try`
+		if ( $iscompleted ) then
+			set try = $maxtries
+		else
+			@ try++
+			sleep 4
+		endif
+	end
+#Trying to get results
+	curl $p4serverurl/wf/`cat $pdir/logs/$this.$$.job`/result -o $pdir/logs/$this.$$.results -H "userID:${p4account}" $curloptions
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this failed in getting the query results from $p4serverurl, got $ret."
+		exit 9
+	endif
 #Providing answer to client application
-xsltproc --stringparam owlquerypic /rightsdraw2/query/$instance.png \
+	xsltproc --stringparam owlquerypic /rightsdraw2/query/$instance.png \
          $pdir/xsl/showQueryResults.xsl $pdir/logs/$this.$$.results > $pdir/logs/$this.$$.answer
-        # --stringparam dipservice "$p4serverurl" $pdir/xsl/showQueryResults.xsl $pdir/logs/$this.$$.results > $pdir/logs/$this.$$.answer
-set ret = $?
-if ( $ret ) then
+	set ret = $?
+	if ( $ret ) then
+		echo "500"
+		echo "Server Error"
+		echo "$this got $ret in processing query results."
+		exit 10
+	endif
+	cat $pdir/logs/$this.$$.answer
+else
+#normally already filtered above during sanity check
 	echo "500"
 	echo "Server Error"
-	echo "$this got $ret in processing query results."
-	exit 10
+	echo "$this unsupported querymode $querymode"
 endif
-cat $pdir/logs/$this.$$.answer
 exit 0
