all last add

diff --git a/www/cgi-bin/query.local/doquery b/www/cgi-bin/query.local/doquery
--- a/www/cgi-bin/query.local/doquery
+++ b/www/cgi-bin/query.local/doquery
@@ -36,6 +36,9 @@ set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut 
 set inquery = `$pdir/bin/clean.querystring $inquery`
 set kp = "null"
 
+set owner = "null"
+set ipentity = "null"
+set relid = "null"
 set permittedaction = "null"
 set isexclusive = "null"
 set accesspolicy = "null"
@@ -141,6 +144,15 @@ while ( $i < $#inquery )
         else if ( "$inquery[$i]" == "negativelanguages" ) then
                 @ i++
                 set negativelanguages = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "owner" ) then
+                @ i++
+                set owner = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "ipentity" ) then
+                @ i++
+                set ipentity = "$inquery[$i]"
+        else if ( "$inquery[$i]" == "relid" ) then
+                @ i++
+                set relid = "$inquery[$i]"
         else
 		echo "400"
 		echo "Bad request "
@@ -225,6 +237,52 @@ else if ( "$permittedaction" != "null" ) then
 		exit 8
 	endif
 	mv $repo/.tmp.$instance $repo/$instance
+	#adding here OwnerItemContext stuff
+	if ( "$owner" != "null" ) then
+		set one = "#aquery"
+		set obj = "http://purl.oclc.org/NET/mvco.owl#actedBy"
+		set twoclass = "http://purl.oclc.org/NET/mvco.owl#User"
+		set twoname = "$owner"
+		xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname  $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+		set ret = $?
+		if ( $ret ) then
+			echo "500"
+			echo "Server Error"
+			echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+			exit 8
+		endif
+		mv $repo/.tmp.$instance $repo/$instance
+	endif
+	if ( "$ipentity" != "null" ) then
+		set one = "#aquery"
+		set obj = "http://purl.oclc.org/NET/mvco.owl#actedOver"
+		set twoclass = "http://purl.oclc.org/NET/mvco.owl#IPEntity"
+		set twoname = "$ipentity"
+		xsltproc --stringparam obj $obj --stringparam one $one --stringparam twoclass $twoclass --stringparam twoname $twoname  $pdir/xsl/addObjProperty.xsl $repo/$instance > $repo/.tmp.$instance
+		set ret = $?
+		if ( $ret ) then
+			echo "500"
+			echo "Server Error"
+			echo "$this failed on addObjProperty ($obj, $one, $twoclass, $twoname) to $instance"
+			exit 8
+		endif
+		mv $repo/.tmp.$instance $repo/$instance
+		if ( "$relid" != "null" ) then
+			set owner = $ipentity
+			set key = "urn:mpeg:mpeg21:2002:01-DII-NS#Identifier"
+			set value = "$relid"
+			xsltproc --stringparam owner $owner --stringparam key $key --stringparam value $value $pdir/xsl/addDataProperty.xsl $repo/$instance > $repo/.tmp.$instance
+			set ret = $?
+			if ( $ret ) then
+				echo "500"
+				echo "Server Error"
+				echo "$this failed on addDataProperty ($owner, $key, $value) to $instance"
+				exit 8
+			endif
+			mv $repo/.tmp.$instance $repo/$instance
+		endif
+	endif
+	#End OwnerItemContext stuff
 
 	# adding exclusivity if given
 	if ( $isexclusive == "on" ) then
@@ -471,6 +529,23 @@ if ( $ret ) then
 	echo "$this got $ret in performing rights matching"
 	exit 9
 endif
+#
+#	Creation of query results locally
+#
+set listaout = `grep true $pdir/logs/$this.$$.rightscompare.out|cut -d'|' -f2 | cut -d'#' -f1 |sort -u`
+echo '<html><body><b>Your query</b>'\
+	'<div style="clear:both"><iframe src="/rightsdraw2/query/'$instance.png'" height="144"></iframe>' \
+	'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/query/$instance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
+	'</div>' \
+	'<b>Found '$#listaout' items matching your query</b><hr/>'
+foreach localinstance ( $listaout )
+	$pdir/bin/mco.dosvg $localinstance
+	echo '<div style="clear:both"><div style="float:left">'$localinstance'<br/><iframe src="/rightsdraw2/mco/'$localinstance.png'" height="144"></iframe></div>' \
+	'<div style="float:left"><p><form target="main" action="../mco/viewedit"><input type="submit" value="viewedit"><input type="hidden" name="instance" value="'$localinstance'"></form>' \
+	'<input type="button" value="Graph" onClick="javascript:window.open('"'"/rightsdraw2/mco/$localinstance.png"'","'"RightsGraph"'","'"width=960,height=800,scrollbars=yes"'"');">' \
+	'</div></div>'
+end
+exit 0
 #
 #	Creation of query results locally
 #
